defaultSemverRangePrefix: ""

packageExtensions:
  "@storybook/core@*":
    peerDependencies:
      webpack: "*"
  "@storybook/react@*":
    peerDependencies:
      typescript: "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
