name: lint

on: [push]

jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.2
        with:
          node-version: 12
          cache: yarn
      - run: yarn install
      - run: yarn lint-all
