name: lint

on: [push]

jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 16
          cache: yarn
      - run: yarn install
      - run: yarn type-check
      - run: yarn lint-all
