name: lint

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 16
          cache: yarn
      - run: yarn install
      - run: yarn type-check
      - run: yarn lint-all
