name: publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Select Tag Name'
        required: true
        type: string
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: yarn install
      - run: yarn test --bail --ci
      - run: npm publish
